### ISSUE TITLE
Yoast + Klarna + Shortcode = fatal

### ISSUE THREAD

**Issue by WillBrubaker** [krokedil/woocommerce-gateway-klarna#110]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

see ticket: 683146-zen

### Expected behavior

- No fatals

### Actual behavior

- Fatal error when saving the page with `[woocommerce_klarna_checkout]` shortcode

### Steps to reproduce the behavior

1. Yoast SEO plugin installed and active (version 5.4.2 locally, 5.4 on customer site)
2. Create a page with the `[woocommerce_klarna_checkout]` shortcode
3. Save that page
4. Witness the sadness of a fatal error similar to:
>Uncaught Error: Call to a member function calculate_shipping() on null in /var/www/nettsider/kunder/landstil.no/html/wp-content/plugins/woocommerce-gateway-klarna/classes/class-klarna-shortcodes.php:229

### Klarna plugin version

- 2.4.1

### WordPress version

- 4.8.1

### WooCommerce version

- 3.1.2

### Klarna country

- Norway

**Comment by zamson** [comment]
Same here

**Comment by slobodan** [comment]
Did this start happening when you updated to a certain WordPress version?

I read about [this issue](https://twitter.com/ircmaxell/status/912306631987417088) yesterday, that was actually a WordPress problem and it affects many plugins, Yoast SEO being the most popular one. Just wanted to check if this is it.

From an [article linked](https://codeseekah.com/2017/09/21/on-wordpress-security-and-contributing/) in that Twitter thread:

```Sites with Yoast SEO installed on them stop functioning in the backend due to some code that relied on numbered placeholders.```

Can you check if this is the case?

**Comment by WillBrubaker** [comment]
@slobodan according to the person who submitted the ticket, there was no WordPress update that coincided with this happening.

**Comment by WillBrubaker** [comment]
That said, this doesn't appear to me to be reproducible with Yoast 5.5.1 - going to ask the ticket submitter what version of Yoast they are on.

**Comment by edvinbrobeck** [comment]
Happens to me too, I am on yoast version 5.6
Looks like it has something to do with parsing the site and trying to compile the shortcode

**Comment by slobodan** [comment]
@edvinbrobeck thanks for more details, I think you're right. The error is caused by WPSEO_Link_Watcher::save_post(), in this line:

```$content = apply_filters( 'the_content', $content );```

It's trying to parse the shortcode (any shortcode) in admin, and our shortcode has reference to WC()->cart in it, which is not available in admin.

I really don't think this is something that should be happening, as shortcodes are only meant to be processed in front-end, where it all works fine, but in order to get this fixed faster, I've added check for WC()->cart before in all three of our shortcodes that makes it possible to save the page when Yoast SEO is active.

You can get the code in `develop` branch: https://github.com/krokedil/woocommerce-gateway-klarna/tree/develop
