### ISSUE TITLE
Klarna gets the wrong order number

### ISSUE THREAD

**Issue by yratof** [krokedil/woocommerce-gateway-klarna#143]
Found an issue with WGK and Sequential order number plugin.

here's the issue:

Post ID:
![image](https://user-images.githubusercontent.com/1001935/33715078-9f5456ae-db51-11e7-879b-bb33f5512f92.png)

Order number: 
![image](https://user-images.githubusercontent.com/1001935/33715088-aa51b16e-db51-11e7-8a0e-afde4886bda3.png)

When Klarna returns to woocommerce, it's told the Post ID, not the order number, which means this post:
![image](https://user-images.githubusercontent.com/1001935/33715100-b845a668-db51-11e7-92fd-fd8659e48a5d.png)

With this order number:
![image](https://user-images.githubusercontent.com/1001935/33715107-bda18b9a-db51-11e7-826a-b9ddc1b80790.png)

Gets all the wrong information & leaves both ordrs in a state of "Incomplete

We need to swap `get_id()` for `get_order_number();`

**Comment by yratof** [comment]
Making a pull request now

**Comment by slobodan** [comment]
It should actually be order ID here, if you look at most uses for this function it's things like:

```add_post_meta( klarna_wc_get_order_id( $order ), '_kco_payment_created', time() );```

That should be order ID, I don't think you can do this with order number.

> When Klarna returns to woocommerce

When exactly did you mean? I'm guessing there is a problem here to solve, but looks like editing that function would not do it.

**Comment by yratof** [comment]
No, the order number should be fine. If you look at the actual function:


```
	/**
	 * get_order_number function.
	 *
	 * Gets the order number for display (by default, order ID).
	 *
	 * @return string
	 */
	public function get_order_number() {
		return (string) apply_filters( 'woocommerce_order_number', $this->get_id(), $this );
	}
```

It simply gets the ID but wraps it in a filter incase anyone modifies it. The problem at the moment is that the order number doesn't have to relate to the post ID. So Klarna isn't return to the correct post when notifying the shop that payment is accepted

**Comment by slobodan** [comment]
I understand what you say, but we mostly use `klarna_wc_get_order_id` function to retrieve or update a post meta field. If we switch this function to return order number that would break our plugin because you can't use post meta fields with a modified order number, ID has to be used instead.

https://codex.wordpress.org/Function_Reference/add_post_meta

**Comment by yratof** [comment]
Then at some point, Klarna is given the wrong ID, because there are now 50 orders in the KCO_Incomplete section of the orders.

Can you retrieve the order from the order number then get the order_id from that?

**Comment by slobodan** [comment]
@yratof could you tell me where exactly this problem happens, and how it is tied to our function?

That function is intended to get order ID from an order, so we can use that order ID to store or retrieve meta fields.

Can you explain what you meant by this:

> When Klarna returns to woocommerce

Returns?

**Comment by yratof** [comment]
I have a post ID that is 100 and the order number is 200
I have a post ID that is 200 and an order number that is 300

Order number 200 pays for their cart. The website finds order ID 200 and marks it as paid.

Both order 200 and 300 are now set to incomplete because klarna is targeting the post_id, not the order number

**Comment by NiklasHogefjord** [comment]
Hi @yratof,

I'm taking over the communication in this issue since Slobodan is focused on finalizing the new Klarna Checkout plugin.

The _klarna_wc_get_order_id()_ function is only used to retrieve Order ID the correct way (without creating any notices depending on the WC version). 

If you use _get_order_number()_ and have Sequential Order Numbers installed it will return the order number created by that plugin. You can not instantiate an order object with an order number created by Sequential Order Numbers plugin.

What sequential order numbers plugin are you using?

**Comment by yratof** [comment]
The official one in the woocommerce store – I believe it's by skyverge, to which their readme states 

> = Why doesn't my payment gateway use this number? =
> 
> For full compatibility with extensions which alter the order number, such as Sequential Order Numbers, WooCommerce extensions should use `$order->get_order_number();` rather than `$order->id` when referencing the order number.
> 
> If your extension is not displaying the correct order number, you can try contacting the developers of your payment gateway to see if it's possible to make this tiny change. Using the order number instead is both compatible with WooCommerce core and our plugin, as without the order number being changed, it will be equal to the order ID.

The issue is that the order ID does not match the order number when using a plugin like this. Currently, when activated, the two plugins clash and klarna payments are no longer being marked as completed / paid. The issue above highlights the problem with the order ID targeting the post ID of a different order

**Comment by yratof** [comment]
To reproduce, create 10 orders in woocommerce without the sequential plugin, then enable it, start your order IDs at 20

The next order will be post ID 11 / Order number 20

Klarna should look for post ID of 20

**Comment by NiklasHogefjord** [comment]
OK, if it is the official one at woocommerce.com by Skyverge (or their free version on wp.org) then it should work. We have several client sites running these two plugins together. 

This demo site also uses it: https://demo.krokedil.se/klarna/ You can make a test purchase there (no real purchases since they are made towards Klarnas playground/test environment).

Compare the order number you get in the confirmation email (or on the order confirmation page) with the param _sid_ in the thank you page url. The _sid_ param being the actual order ID.
