### ISSUE TITLE
Post number is parsed incorrectly

### ISSUE THREAD

**Issue by SirRahikkala** [krokedil/woocommerce-gateway-klarna#145]
Please submit issues and pull requests to Krokedil repo - https://github.com/krokedil/woocommerce-gateway-klarna 

### Expected behavior

-When customer enters post number/code in whatever format at 1st stage of cart, the next stage the post code has removed spaces.
This is big issue with logistics companies and functionalities which do sanity checks on post codes. For example DHL requires that all post codes are exactly as they are required in specific countries.
See this list of global variants of post codes: http://www.mapanet.eu/EN/resources/Postal-Format.asp
For maintaining Klarna and customer compatibility globally, post codes should not be modified from the format the customer enters. I emphasize that this is not DHL etc. issue if customer entry is not respected.

### Actual behavior

-For example Stockholm post code 111 12 turns into 11112.

### Steps to reproduce the behavior

-Enter post code as above and move forward from 1st klarna payment stage to next and the post code space is stripped.

### Klarna plugin version

- 2.5.4

### WordPress version

-4.9.1

### WooCommerce version

- 3.2.5.

### Klarna country

-Sweden and Finland
![33494796-2c8484ba-d6cd-11e7-87fd-57fae61ce13e](https://user-images.githubusercontent.com/7370720/33759675-dc716224-dc0b-11e7-9b8a-99113f53a4ad.png)

**Comment by NiklasHogefjord** [comment]
Hi,
What happen in the Klarna Checkout iframe is handled by Klarna. This is nothing we can control from the WooCommerce plugin. If you have questions about how customer data is handled in Klarnas system I would recommend you to get in direct contact with Klarna.

If this is an issue for DHL I actually would suggest that the plugin (or the service) that sends the customer data to DHL would perform this check and send it in the approved format.

I'm closing this issue since there is nothing we can do in the plugin to change this.

**Comment by SirRahikkala** [comment]
Ok, thank you! Klarna confirmed that it is indeed their "issues" but they are reluctant to rectify it.
