### ISSUE TITLE
Translation - Finnish

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/woocommerce-gateway-klarna#185]
KPM - Update translation

There is a suggestion from a client to change the translation from:

- Where it states: **_henkilötunnus_** we should add **_Y-tunnus_**

- Instead of **_DDMMYY-XXXX_** it should be **_PPKKVV-XXXX_**

![image 2](https://user-images.githubusercontent.com/2573170/45303357-eecaaa00-b515-11e8-85e0-db8c8bd8f9de.png)

**Comment by kristibarbosky** [comment]
created https://jira.int.klarna.net/jira/browse/KRED-3687

**Comment by kristibarbosky** [comment]
@boozebrorsan - the Klarna KPM team said they don't control those translations in the backend.  To help us determine the correct code that is handling those fields, could you provide us more info, such as: 

1. the Klarna EID that is used for this request

2. the URL of the store

thanks!

**Comment by boozebrorsan** [comment]
Hi Kristi,

Sorry for a diffuse ticket from my side I realize that it was clear in my head what I wanted to ask but in the text it was very very very unclear when I read it again ;)

Here is what I wanted to ask:

- Can we get a confirmation from Klarna that the translation suggested is correct in the finnish language so we can update that in the plugin (we controll this in the plugin)? Or should the current translation in finnish be left as it is? Or can Klarna Finland give us an answer what is the correct translation in this case? @kristibarbosky

**Comment by kristibarbosky** [comment]
thanks for the clarification @boozebrorsan - working to track down the appropriate Klarna person to answer this

**Comment by kristibarbosky** [comment]
@boozebrorsan - I've found the right person to help with this.  She says:

I can see that in the link that you provided, the suggestion is to change personal number (henkilötunnus) to organization number (y-tunnus). So if these purchases are for companies, then yes the change is correct. But if you change the first field to org number then the guidance to fill it in should not be there, since the org number obviously does not refer to a birthday but is a random number (as far as I know). 

Do let me know if anything is unclear or if you need help with anything else!

**Comment by boozebrorsan** [comment]
The solution here is to manually translate the specific words via a WordPress-plugin like Locotranslate.
