### ISSUE TITLE
Klarna Checkout doesn't update/reload when cart changes

### ISSUE THREAD

**Issue by jelgblad** [krokedil/woocommerce-gateway-klarna#28]
### Expected behavior

Klarna Checkout updates/reloads when cart changes (add/remove coupon code or change item quantity).

### Actual behavior

Klarna Checkout doesn't update/reload when cart changes.
However Klarna Checkout seem to reload immediately after the +/- buttons are clicked on an item. But the Order Total doesn't update until Update Cart is clicked (which doesn't update Klarna Checkout).

### Steps to reproduce the behavior

- Add `[woocommerce_klarna_checkout]` to Klarna Checkout page
- Add `[woocommerce_cart]` to Klarna Checkout page

**In frontend**:

- Add item to cart
- Go to checkout
- Change something in cart and klick Update Cart
- Nothing happens... until customer hits F5

### WordPress version

4.7

### WooCommerce version

2.6.11

### Klarna country

Sweden

**Comment by NiklasHogefjord** [comment]
The ajax functionality does not work when having the Klarna Checkout iframe on the same page as the WooCommerce cart. This worked in WooCommerce versions prior to v2.6 but has never been the recommended way to setup Klarna Checkout.

If you want to add a cart widget to the Klarna Checkout page we offer this via a separate short code. You can read more about this in the documentation here: https://docs.woocommerce.com/document/klarna/#section-7

I'm closing this issue since it isn't a bug.
